
    version: '3.7'
    services:
    
      server:
        image: fl_chaos
        command: [ "python", "/code/server.py"]
        environment:
          FL_STRATEGY: FedAvg
          # "FastAndSlow", "FaultTolerantFedAvg", "FedAdagrad", "FedAdam", "FedAvg",
          # "FedAvgAndroid", "FedAvgM", "FedFSv0", "FedFSv1", "FedYogi", "QFedAvg"
          FL_NUM_OF_ROUNDS: 3
          FL_FRACTION_FIT: 0.1
          FL_FRACTION_EVAL: 0.1
          FL_MIN_EVAL_CLIENTS: 1
          FL_MIN_FIT_CLIENTS: 1
          FL_MIN_AVAILABLE_CLIENTS: 1
          FL_PROFILE_PREFIX: pytorch_mobilenetv2-CIFAR10-FedAvg-false-1-2023-small
          FL_BACKEND: pytorch_mobilenetv2
          FL_DATASET: CIFAR10
          FL_EVAL_DATASET: "false"
          HTTP_PROXY: 
          HTTPS_PROXY: 
          https_proxy: 
          http_proxy: 
          FL_TEST_SET_SIZE: 1000
          FL_TRAINING_SET_SIZE: 5000
          FL_EPOCHS: 1
        volumes:
          - /home/moses/back-up/research/FDLC/container/code/:/code/
          - /home/ubuntu/research/FDLC/fogify/profile/server/:/profile/
          - /home/ubuntu/research/FDLC/fogify/data/:/data/
        expose:
        - 8080
    
      client_0:
        image: fl_chaos
        depends_on:
          - server
        command: 'sh -c "sleep 20 && python /code/client.py"'
        environment:
          FL_SERVER: server
          FL_BACKEND: pytorch_mobilenetv2
          FL_DATASET: CIFAR10
          FL_NODES: 1
          FL_NODE_ID: 0
          FL_DATASET_DISTRIBUTION: flat
          FL_DATASET_RANDOM: 'False'
          FL_DATASET_DISTRIBUTION_PARAMETERS: '{"random_state":1}'
          FL_PROFILE_PREFIX: 0-pytorch_mobilenetv2-CIFAR10-1-2023-small
          HTTP_PROXY: 
          HTTPS_PROXY: 
          https_proxy: 
          http_proxy: 
          FL_TRAINING_SET_SIZE: 50000
          FL_TEST_SET_SIZE: 10000
          FL_EPOCHS: 1

        volumes:
          - /home/moses/back-up/research/FDLC/container/code/:/code/
          - /home/ubuntu/research/FDLC/fogify/profile/clients/:/profile/
          - /home/ubuntu/research/FDLC/fogify/data/:/data/

    