version: '3.7'
services:
  server:
    image: fl_chaos
    build:
      .
    command: [ "python", "/code/server.py"]
    environment:
      FL_STRATEGY: FedAvg
      # "FastAndSlow", "FaultTolerantFedAvg", "FedAdagrad", "FedAdam", "FedAvg",
      # "FedAvgAndroid", "FedAvgM", "FedFSv0", "FedFSv1", "FedYogi", "QFedAvg"
      FL_NUM_OF_ROUNDS: 2
      FL_FRACTION_FIT: 0.1
      FL_FRACTION_EVAL: 0.1
      FL_MIN_EVAL_CLIENTS: 2
      FL_MIN_FIT_CLIENTS: 2
      FL_MIN_AVAILABLE_CLIENTS: 2
      FL_BACKEND: pytorch_light
      FL_DATASET: MNIST # CIFAR10 / CIFAR100 / MNIST
      FL_EVAL_DATASET: "false"
    volumes:
      - /home/ubuntu/research/FDLC/container/code/:/code/
      - /home/ubuntu/research/FDLC/fogify/profile/server/:/profile/
      - /home/ubuntu/research/FDLC/fogify/data/:/data/
  client_1:
    image: fl_chaos
    depends_on:
      - server
    build:
      .
    command: 'sh -c "sleep 20 && python /code/client.py"'
    environment:
      FL_HOST: 1  # FL_client_id
      FL_SERVER: server
      FL_BACKEND: pytorch_light  # pytorch/tensorflow/pytorch_light/sklearn/mxnet
      FL_DATASET: MNIST
      FL_TRAINING_SET_SIZE: 500
      FL_TEST_SET_SIZE: 100
      FL_NUM_OF_THREADS: 4
      TF_NUM_INTRAOP_THREADS: 4
      TF_NUM_INTEROP_THREADS: 4
    volumes:
      - /home/ubuntu/research/FDLC/container/code/:/code/
      - /home/ubuntu/research/FDLC/fogify/profile/client_1/:/profile/
      - /home/ubuntu/research/FDLC/fogify/data/:/data/
  client_2:
    image: fl_chaos
    depends_on:
      - server
    build:
      .
    command: 'sh -c "sleep 20 && python /code/client.py"'
    environment:
      FL_HOST: 2
      FL_SERVER: server
      FL_BACKEND: pytorch_light  # pytorch/tensorflow/pytorch_light
      FL_DATASET: MNIST
      FL_NUM_OF_THREADS: 4
      FL_TRAINING_SET_SIZE: 500
      FL_TEST_SET_SIZE: 100
      TF_NUM_INTRAOP_THREADS: 4
      TF_NUM_INTEROP_THREADS: 4
    volumes:
      - /home/ubuntu/research/FDLC/fogify/data/:/data/
      - /home/ubuntu/research/FDLC/fogify/profile/client_2/:/profile/
      - /home/ubuntu/research/FDLC/container/code/:/code/
